const states = {
    "ANDAMAN And NICOBAR ISLANDS": [
    "N & M ANDAMAN",
    "NICOBAR",
    "SOUTH ANDAMAN"
    ],
    "ANDHRA PRADESH": [
    "ADILABAD",
    "ANANTAPUR",
    "CHITTOOR",
    "EAST GODAVARI",
    "GUNTUR",
    "HYDERABAD",
    "KARIMNAGAR",
    "KHAMMAM",
    "KRISHNA",
    "KUDDAPAH",
    "KURNOOL",
    "MAHABUBNAGAR",
    "MEDAK",
    "NALGONDA",
    "NELLORE",
    "NIZAMABAD",
    "PRAKASAM",
    "RANGAREDDY",
    "SRIKAKULAM",
    "VISAKHAPATNAM",
    "VIZIANAGARAM",
    "WARANGAL",
    "WEST GODAVARI"
    ],
    "ARUNACHAL PRADESH": [
    "ANJAW (LOHIT)",
    "CHANGLANG",
    "DIBANG VALLEY",
    "EAST KAMENG",
    "EAST SIANG",
    "KURUNG KUMEY",
    "LOHIT",
    "LOW SUBANSIRI",
    "LOWER DIBANG",
    "PAPUM PARE",
    "SUBANSIRI F.D",
    "TAWANG(W KAME",
    "TIRAP",
    "UPPER SIANG",
    "WEST KAMENG",
    "WEST SIANG"
    ],
    "ASSAM": [
    "BAKSA BARPETA",
    "BARPETA",
    "BONGAIGAON",
    "CACHAR",
    "CHIRANG(BONGAI",
    "DARRANG",
    "DHEMAJI(LAKHI",
    "DHUBRI",
    "DIBRUGARH",
    "GOALPARA",
    "GOLAGHAT",
    "HAILAKANDI",
    "JORHAT",
    "KAMRUP",
    "KAMRUP METROP",
    "KARBI ANGLONG",
    "KARIMGANJ",
    "KOKRAJHAR",
    "LAKHIMPUR",
    "MORIGAON",
    "NAGAON",
    "NALBARI",
    "NORTH CACHAR",
    "SHONITPUR",
    "SIVASAGAR",
    "TINSUKIA",
    "UDALGURI(DARA"
    ],
    "BIHAR": [
    "ARARIA",
    "ARWAL",
    "AURANGABAD",
    "BANKA",
    "BEGUSARAI",
    "BHABUA",
    "BHAGALPUR",
    "BHOJPUR",
    "BUXAR",
    "DARBHANGA",
    "EAST CHAMPARAN",
    "GAYA",
    "GOPALGANJ",
    "JAHANABAD",
    "JAMUI",
    "KATIHAR",
    "KHAGARIA",
    "KISHANGANJ",
    "LAKHISARAI",
    "MADHEPURA",
    "MADHUBANI",
    "MUNGER",
    "MUZAFFARPUR",
    "NALANDA",
    "NAWADA",
    "PATNA",
    "PURNEA",
    "ROHTAS",
    "SAHARSA",
    "SAMASTIPUR",
    "SARAN",
    "SHEIKHPURA",
    "SHEOHAR",
    "SITAMARHI",
    "SIWAN",
    "SUPAUL",
    "VAISHALI",
    "WEST CHAMPARAN"
    ],
    "CHANDIGARH": [
    "CHANDIGARH"
    ],
    "CHATISGARH": [
    "BASTAR",
    "BIJAPUR",
    "BILASPUR",
    "DANTEWADA",
    "DHAMTARI",
    "DURG",
    "JANJGIR-CHAMP",
    "JASHPUR",
    "KANKER (NORH",
    "KORBA",
    "KORIYA",
    "KOWARDHA (KAB",
    "MAHASAMUND",
    "NARAYANPUR",
    "RAIGARH",
    "RAIPUR",
    "RAJNANDGAON",
    "SURGUJA"
    ],
    "DADAR NAGAR HAVELI": [
    "DNH"
    ],
    "DAMAN AND DUI": [
    "DAMAN",
    "DIU"
    ],
    "DELHI": [
    "CENTRAL DELHI",
    "EAST DELHI",
    "NE DELHI",
    "NEW DELHI",
    "NORTH DELHI",
    "NW DELHI",
    "SOUTH DELHI",
    "SW DELHI",
    "WEST DELHI"
    ],
    "GOA": [
    "NORTH GOA",
    "SOUTH GOA"
    ],
    "GUJARAT": [
    "AHMEDABAD",
    "AMRELI",
    "ANAND(KHR)",
    "BANASKANTHA",
    "BARODA",
    "BHARUCH",
    "BHAVNAGAR",
    "DAHOD(PNML)",
    "DANGS",
    "GANDHINAGAR",
    "JAMNAGAR",
    "JUNAGADH",
    "KHEDA",
    "KUTCH",
    "MEHSANA",
    "NARMADA(BRC)",
    "NAVSARI(VSD)",
    "PANCHMAHALS",
    "PATAN(MHSN)",
    "PORBANDAR",
    "RAJKOT",
    "SABARKANTHA",
    "SURAT",
    "SURENDRANAGAR",
    "TAPI(SRT)",
    "VALSAD"
    ],
    "HARYANA": [
    "AMBALA",
    "BHIWANI",
    "FARIDABAD",
    "FATEHABAD",
    "GURGAON",
    "HISAR",
    "JHAJJAR",
    "JIND",
    "KAITHAL",
    "KARNAL",
    "KURUKSHETRA",
    "MAHENDRAGARH",
    "MEWAT",
    "PALWAL(FRD)",
    "PANCHKULA",
    "PANIPAT",
    "REWARI",
    "ROHTAK",
    "SIRSA",
    "SONEPAT(RTK)",
    "YAMUNANAGAR"
    ],
    "HIMACHAL": [
    "BILASPUR",
    "CHAMBA",
    "HAMIRPUR",
    "KANGRA",
    "KINNAUR",
    "KULLU",
    "LAHUL & SPITI",
    "MANDI",
    "SHIMLA",
    "SIRMAUR",
    "SOLAN",
    "UNA"
    ],
    "JAMMU AND KASHMIR": [
    "ANANTNAG",
    "BADGAM",
    "BANDIPORE",
    "BARAMULLA",
    "DODA",
    "GANDERWAL",
    "JAMMU",
    "KARGIL",
    "KATHUA",
    "KISTWAR",
    "KULGAM/(ANT)",
    "KUPWARA",
    "LADAKH (LEH)",
    "POONCH",
    "PULWAMA",
    "RAJOURI",
    "RAMBAN(DDA)",
    "REASI",
    "SAMBA",
    "SHOPAN",
    "SRINAGAR",
    "UDHAMPUR"
    ],
    "JHARKHAND": [
    "BOKARO",
    "CHATRA",
    "DEOGHAR",
    "DHANBAD",
    "DUMKA",
    "EAST SINGHBHU",
    "GARHWA",
    "GIRIDIH",
    "GODDA",
    "GUMLA",
    "HAZARIBAG",
    "JAMTARA",
    "KHUNTI(RANCHI",
    "KODERMA",
    "LATEHAR",
    "LOHARDAGA",
    "PAKUR",
    "PALAMU",
    "RAMGARH",
    "RANCHI",
    "SAHIBGANJ",
    "SERAIKELA-KHA",
    "SIMDEGA",
    "WEST SINGHBHUM"
    ],
    "KARNATAKA": [
    "BAGALKOTE",
    "BANGALORE RUR",
    "BANGALORE URB",
    "BELGAM",
    "BELLARY",
    "BIDAR",
    "BIJAPUR",
    "CHAMARAJANAGA",
    "CHICKBALLAPUR",
    "CHIKMAGALUR",
    "CHITRADURGA",
    "DAKSHIN KANDA",
    "DAVANGERE",
    "DHARWAD",
    "GADAG",
    "GULBARGA",
    "HASSAN",
    "HAVERI",
    "KODAGU",
    "KOLAR",
    "KOPPAL",
    "MANDYA",
    "MYSORE",
    "RAICHUR",
    "RAMNAGAR(BNGR)",
    "SHIMOGA",
    "TUMKUR",
    "UDUPI",
    "UTTAR KANNADA",
    "YADGIR"
    ],
    "KERALA": [
    "ALAPPUZHA",
    "CANNUR",
    "ERNAKULAM",
    "IDUKKI",
    "KASARGOD",
    "KOLLAM",
    "KOTTAYAM",
    "KOZHIKODE",
    "MALAPPURAM",
    "PALAKKAD",
    "PATHANAMTHITTA",
    "THIRUVANANTHA",
    "THRISSUR",
    "WAYANAD"
    ],
    "LAKSHADWEEP": [
    "LAKSHADWEEP"
    ],
    "MADHYA PRADESH": [
    "ALIRAJPUR(JBA)",
    "ANUPPUR(SHAHD",
    "ASHOKNAGAR(GNA",
    "BALAGHAT",
    "BARWANI",
    "BETUL",
    "BHIND",
    "BHOPAL",
    "BURHANPUR",
    "CHHATARPUR",
    "CHHINDWARA",
    "DAMOH",
    "DATIA",
    "DEWAS",
    "DHAR",
    "DINDORI",
    "GUNA",
    "GWALIOR",
    "HARDA",
    "HOSHANGABAD",
    "INDORE",
    "JABALPUR",
    "JHABUA",
    "KATNI",
    "KHANDWA",
    "KHARGONE",
    "MANDLA",
    "MANDSAUR",
    "MORENA",
    "NARSINGHPUR",
    "NEEMUCH",
    "PANNA",
    "RAISEN",
    "RAJGARH",
    "RATLAM",
    "REWA",
    "SAGAR",
    "SATNA",
    "SEHORE",
    "SEONI",
    "SHAHDOL",
    "SHAJAPUR",
    "SHEOPUR",
    "SHIVPURI",
    "SIDHI",
    "SINGRAULI",
    "TIKAMGARH",
    "UJJAIN",
    "UMARIA",
    "VIDISHA"
    ],
    "MAHARASHTRA": [
    "AHMEDNAGAR",
    "AKOLA",
    "AMRAVATI",
    "AURANGABAD",
    "BEED",
    "BHANDARA",
    "BULDHANA",
    "CHANDRAPUR",
    "DHULE",
    "GADCHIROLI",
    "GONDIA",
    "HINGOLI",
    "JALGAON",
    "JALNA",
    "KOLHAPUR",
    "LATUR",
    "MUMBAI CITY",
    "MUMBAI SUB",
    "NAGPUR",
    "NANDED",
    "NANDURBAR",
    "NASHIK",
    "OSMANABAD",
    "PARBHANI",
    "PUNE",
    "RAIGAD",
    "RATNAGIRI",
    "SANGLI",
    "SATARA",
    "SINDHUDURG",
    "SOLAPUR",
    "THANE",
    "WARDHA",
    "WASHIM",
    "YAVATMAL"
    ],
    "MANIPUR": [
    "BISHNUPUR",
    "CHANDEL",
    "CHURACHANDPUR",
    "IMPHAL EAST",
    "IMPHAL WEST",
    "SENAPATI",
    "TAMENGLONG",
    "THOUBAL",
    "UKHRUL"
    ],
    "MEGHALAYA": [
    "EAST GARO HIL",
    "EAST KHASI HI",
    "JAINTIA HILLS",
    "RI-BHOI",
    "SOUTH GARO HI",
    "W KHASI HILL",
    "WEST GARO HIL"
    ],
    "MIZORAM": [
    "AIZAWL",
    "CHAMPHAI",
    "CHHIMTUIPUI",
    "KOLASIB",
    "LAWNGTLAI",
    "LUNGLEI",
    "MAMIT",
    "SAIHA",
    "SERCHHIP"
    ],
    "NAGALAND": [
    "DIMAPUR",
    "KEPHRIE",
    "KOHIMA",
    "LONGLENG",
    "MOKOKCHUNG",
    "MON",
    "PEREN",
    "PHEK",
    "TUENSANG",
    "WOKHA",
    "ZUNHEBOTO"
    ],
    "ORISSA": [
    "ANGUL",
    "BALASORE",
    "BARGARH",
    "BHADRAK",
    "BOLANGIR",
    "BOUDHGARH",
    "CUTTACK",
    "DEOGARH",
    "DHENKANAL",
    "GAJAPATI",
    "GANJAM",
    "JAGATSINGHAPU",
    "JAJPUR",
    "JHARSUGUDA",
    "KALAHANDI",
    "KANDHAMAL/PHU",
    "KENDRAPARA",
    "KEONDJHARGARH",
    "KHURDA",
    "KORAPUT",
    "MALKANGIRI",
    "MAYURBHANJ",
    "NAWAPARA",
    "NAWARANGPUR",
    "NAYAGARH",
    "PURI",
    "RAYAGADA",
    "SAMBALPUR",
    "SONEPUR",
    "SUNDARGARH"
    ],
    "PONDICHERRY": [
    "KARAIKAL",
    "MAHE",
    "PONDICHERRY",
    "YANAM"
    ],
    "PUNJAB": [
    "AMRITSAR",
    "BARNALA",
    "BATHINDA",
    "FARIDKOT",
    "FATEHGARH SAH",
    "FEROZEPUR",
    "GURDASPUR",
    "HOSHIARPUR",
    "JALANDHAR",
    "KAPURTHALA",
    "LUDHIANA",
    "MANSA",
    "MOGA",
    "MUKTSAR",
    "NAWANSHAHR",
    "PATIALA",
    "RUPNAGAR",
    "SANGRUR",
    "SAS NAGAR(MGA)",
    "TARN TARAN"
    ],
    "RAJASTHAN": [
    "AJMER",
    "ALWAR",
    "BANSWARA",
    "BARAN",
    "BARMER",
    "BHARATPUR",
    "BHILWARA",
    "BIKANER",
    "BUNDI",
    "CHITTORGARH",
    "CHURU",
    "DAUSA",
    "DHOLPUR",
    "DUNGARPUR",
    "HANUMANGARH",
    "JAIPUR",
    "JAISALMER",
    "JALORE",
    "JHALAWAR",
    "JHUNJHUNU",
    "JODHPUR",
    "KARAULI",
    "KOTA",
    "NAGAUR",
    "PALI",
    "PRATAPGARH(CHT",
    "RAJSAMAND",
    "SAWAI MADHOPUR",
    "SIKAR",
    "SIROHI",
    "SRI GANGANAGA",
    "TONK",
    "UDAIPUR"
    ],
    "SIKKIM": [
    "EAST SIKKIM",
    "NORTH SIKKIM",
    "SOUTH SIKKIM",
    "WEST SIKKIM"
    ],
    "TAMIL NADU": [
    "ARIYALUR",
    "CHENNAI",
    "COIMBATORE",
    "CUDDALORE",
    "DHARMAPURI",
    "DINDIGUL",
    "ERODE",
    "KANCHIPURAM",
    "KANYAKUMARI",
    "KARUR",
    "KRISHNAGIRI",
    "MADURAI",
    "NAGAPATTINAM",
    "NAMAKKAL",
    "NILGIRIS",
    "PERAMBALUR",
    "PUDUKKOTTAI",
    "RAMANATHAPURA",
    "SALEM",
    "SIVAGANGA",
    "THANJAVUR",
    "THENI",
    "THOOTHUKUDI",
    "TIRUCHIRAPPAL",
    "TIRUNELVELI",
    "TIRUPUR",
    "TIRUVALLUR",
    "TIRUVANNAMALA",
    "TIRUVARUR",
    "VELLORE",
    "VILUPPURAM",
    "VIRUDHUNAGAR"
    ],
    "TRIPURA": [
    "DHALAI",
    "NORTH TRIPURA",
    "SOUTH TRIPURA",
    "WEST TRIPURA"
    ],
    "UTTAR PRADESH": [
    "AGRA",
    "ALIGARH",
    "ALLAHABAD",
    "AMBEDKAR NAGAR",
    "AURAIYA",
    "AZAMGARH",
    "BADAUN",
    "BAGPAT",
    "BAHRAICH",
    "BALLIA",
    "BALRAMPUR",
    "BANDA",
    "BARABANKI",
    "BAREILLY",
    "BASTI",
    "BIJNOR",
    "BULANDSHAHAR",
    "CHANDAULI",
    "DEORIA",
    "ETAH",
    "ETAWAH",
    "FAIZABAD",
    "FARRUKHABAD",
    "FATEHPUR",
    "FIROZABAD",
    "GAUTAM BUDDHA",
    "GHAZIABAD",
    "GHAZIPUR",
    "GONDA",
    "GORAKHPUR",
    "HAMIRPUR",
    "HARDOI",
    "JALAUN",
    "JAUNPUR",
    "JHANSI",
    "JYOTIBA PHULE",
    "KANNAUJ",
    "KANPUR DEHAT",
    "KANPUR NAGAR",
    "KANSHIRAM NAG",
    "KAUSHAMBI",
    "KHERI LAKHIMP",
    "KUSHINAGAR",
    "LALITPUR",
    "LUCKNOW",
    "MAHAMAYA NAGA",
    "MAHARAJGANJ",
    "MAHOBA",
    "MAINPURI",
    "MATHURA",
    "MAU",
    "MEERUT",
    "MIRZAPUR",
    "MORADABAD",
    "MUZAFFARNAGAR",
    "PILIBHIT",
    "PRATAPGARH",
    "RAE BARELI",
    "RAMPUR",
    "SAHARANPUR",
    "SAHUJI MAHARA",
    "SANT KABIR NGR",
    "SANT RAVIDAS",
    "SHAHJAHANPUR",
    "SHRAVASTI NGR",
    "SIDDHARTH NGR",
    "SITAPUR",
    "SONBHADRA",
    "SULTANPUR",
    "UNNAO",
    "VARANASI"
    ],
    "UTTARANCHAL": [
    "ALMORA",
    "BAGESHWAR",
    "CHAMOLI",
    "CHAMPAWAT",
    "DEHRADUN",
    "GARHWAL PAURI",
    "GARHWAL TEHRI",
    "HARIDWAR",
    "NAINITAL",
    "PITHORAGARH",
    "RUDRAPRAYAG",
    "UDHAM SINGH N",
    "UTTARKASHI"
    ],
    "WEST BENGAL": [
    "BANKURA",
    "BIRBHUM",
    "BURDWAN",
    "COOCH BEHAR",
    "DARJEELING",
    "EAST MIDNAPOR",
    "HOOGHLY",
    "HOWRAH",
    "JALPAIGURI",
    "KOLKATA",
    "MALDA",
    "MURSHIDABAD",
    "NADIA",
    "NORTH 24 PARG",
    "NORTH DINAJPUR",
    "PURULIA",
    "SOUTH 24 PARG",
    "SOUTH DINAJPUR",
    "WEST MIDNAPOR"
    ]
    }
export default states;